# Generated by Django 5.0.6 on 2024-07-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0003_alter_bag_bag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='bag_price',
            field=models.PositiveIntegerField(verbose_name='قیمت کیف'),
        ),
    ]
