# Generated by Django 5.0.6 on 2024-07-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0004_alter_bag_bag_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='bag_image',
            field=models.ImageField(default='media/defult_image.jpeg', upload_to='media/', verbose_name='عکس کیف'),
        ),
    ]
