# Generated by Django 5.0.6 on 2024-07-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_name', models.CharField(max_length=100, verbose_name='اسم کیف')),
                ('bag_number', models.IntegerField(verbose_name='تعداد کیف')),
                ('bag_price', models.IntegerField(verbose_name='قیمت کیف')),
                ('Type', models.IntegerField(choices=[(1, 'کیف مدرسه'), (2, 'کیف باشگاه'), (3, 'کیف پول'), (4, 'گیف مسافرتی')], verbose_name='نوع کیف')),
            ],
        ),
    ]
