# Generated by Django 5.0.6 on 2024-07-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='bag_price',
            field=models.BigIntegerField(verbose_name='قیمت کیف'),
        ),
    ]
