# Generated by Django 5.0.6 on 2024-07-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0002_alter_bag_bag_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='bag_name',
            field=models.CharField(max_length=100, verbose_name='نام برند'),
        ),
    ]
