# Generated by Django 5.0.6 on 2024-07-22 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0005_bag_bag_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='bag_image',
        ),
    ]
